# openapi2-functions.yaml
swagger: '2.0'
info:
  title: podlink
  description: API that performs the episode and episode report
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /episodes:
    get:
      summary: Retrieve a paginated list of episodes in descending order by published date
      operationId: podlink-episodes
      x-google-backend:
        address: https://us-east4-mosaic-fertilizantes.cloudfunctions.net/podlink-episodes
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /episodes_report:
    get:
      summary: Retrieve analytics of downloads per day for an entire podcast
      operationId: podlink-episodes-report
      x-google-backend:
        address: https://us-east4-mosaic-fertilizantes.cloudfunctions.net/podlink-episodes-report
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"